spring:
    application:
        name: vehicle_purchase
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/vehicle_purchase?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
    aop:
        auto: true

server:
    port: 8080

mybatis:
    mapper-locations: classpath:/mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true

pagehelper:
    helperDialect: mysql
    supportMethodsArguments: true
    params: count=countSql
    default-count: false

file:
    staticAccessPath: /files/**
    uploadFolder: D://FILE_SERVER/